name: lint js

on:
  push:
    paths:
      - ".github/workflows/lint-js.yml"
      - "src/*"
      - "*.ts"
      - "crates/**/*.ts"
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
      - name: Install Dependencies
        working-directory: ./
        run: pnpm install
      - name: Run ts:check
        working-directory: ./
        run: pnpm run ts:check
      - name: Run lint
        working-directory: ./
        run: pnpm run lint
      - name: Run format
        working-directory: ./
        run: pnpm run format:check
